name: markdown_editor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  universal_io: ^2.0.4
  flutter_rust_bridge: 1.6.0
  flutter_riverpod: 1.0.0-dev.10
  riverpod: 1.0.0-dev.10
  flutter_markdown: ^0.6.7
  flutter_math_fork: ^0.5.0
  url_launcher: ^6.0.12
  shared_preferences: ^2.0.8
  text: ^0.2.0
  statsfl: ^2.0.1+1
  file_picker: ^4.2.1
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/markdown_reference.md
  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic
