[package]
name = "rust-md-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0.0"
# pulldown-cmark = "0.8.0"

[dependencies.pulldown-cmark]
version = "0.8.0"
default_features = false
features = ["simd"]
