[package]
name = "rust-md"
version = "0.1.0"
authors = ["Viet Dinh <54ckb0y789@gmail.com>"]
edition = "2018"
description = "Various utilities for Markdown"
repository = "https://github.com/Desdaemon/markdown_editor"
license = ""

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.63", features = ["serde-serialize"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
serde-wasm-bindgen = { version = "0.3.0", optional = true }
quick-xml = "0.22.0"
js-sys = "0.3.51"
# quick-xml = "0.22.0"
# nom = "6.2.1"

[dependencies.pulldown-cmark]
version = "0.8.0"
default-features = false
features = ["simd"]

[dev-dependencies]
assert-json-diff = "2.0.1"
wasm-bindgen-test = "0.3.13"

[profile.release]
# see https://doc.rust-lang.org/rustc/codegen-options/index.html#opt-level
opt-level = "s"
# opt-level = 3
lto = true
